INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('1', 'Can add log entry', '1', 'add_logentry');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('2', 'Can change log entry', '1', 'change_logentry');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('3', 'Can delete log entry', '1', 'delete_logentry');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('4', 'Can view log entry', '1', 'view_logentry');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('5', 'Can add permission', '2', 'add_permission');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('6', 'Can change permission', '2', 'change_permission');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('7', 'Can delete permission', '2', 'delete_permission');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('8', 'Can view permission', '2', 'view_permission');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('9', 'Can add group', '3', 'add_group');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('10', 'Can change group', '3', 'change_group');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('11', 'Can delete group', '3', 'delete_group');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('12', 'Can view group', '3', 'view_group');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('13', 'Can add user', '4', 'add_user');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('14', 'Can change user', '4', 'change_user');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('15', 'Can delete user', '4', 'delete_user');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('16', 'Can view user', '4', 'view_user');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('17', 'Can add content type', '5', 'add_contenttype');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('18', 'Can change content type', '5', 'change_contenttype');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('19', 'Can delete content type', '5', 'delete_contenttype');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('20', 'Can view content type', '5', 'view_contenttype');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('21', 'Can add session', '6', 'add_session');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('22', 'Can change session', '6', 'change_session');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('23', 'Can delete session', '6', 'delete_session');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('24', 'Can view session', '6', 'view_session');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('25', 'Can add notice', '7', 'add_notice');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('26', 'Can change notice', '7', 'change_notice');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('27', 'Can delete notice', '7', 'delete_notice');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('28', 'Can view notice', '7', 'view_notice');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('29', 'Can add table_ five', '8', 'add_table_five');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('30', 'Can change table_ five', '8', 'change_table_five');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('31', 'Can delete table_ five', '8', 'delete_table_five');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('32', 'Can view table_ five', '8', 'view_table_five');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('33', 'Can add table_ six', '9', 'add_table_six');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('34', 'Can change table_ six', '9', 'change_table_six');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('35', 'Can delete table_ six', '9', 'delete_table_six');
INSERT INTO "auth_permission" ("id", "name", "content_type_id", "codename") VALUES ('36', 'Can view table_ six', '9', 'view_table_six');
