INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES ('1', 'admin', 'logentry');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES ('3', 'auth', 'group');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES ('2', 'auth', 'permission');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES ('4', 'auth', 'user');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES ('5', 'contenttypes', 'contenttype');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES ('7', 'myapp', 'notice');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES ('8', 'myapp', 'table_five');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES ('9', 'myapp', 'table_six');
INSERT INTO "django_content_type" ("id", "app_label", "model") VALUES ('6', 'sessions', 'session');
